version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nobat-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nobat_db_dev
      POSTGRES_USER: nobat_user
      POSTGRES_PASSWORD: nobat_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - nobat-network-dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nobat_user -d nobat_db_dev']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: nobat-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass nobat_redis_password
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - nobat-network-dev
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nobat Backend Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nobat-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: nobat_user
      DB_PASSWORD: nobat_password
      DB_DATABASE: nobat_db_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: nobat_redis_password
      REDIS_DB: 0
      JWT_SECRET: nobat_jwt_secret_key_2024_dev
      JWT_REFRESH_SECRET: nobat_refresh_secret_key_2024_dev
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      OTP_EXPIRES_IN: 300
      THROTTLE_TTL: 60000
      THROTTLE_LIMIT: 10
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nobat-network-dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nobat-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nobat.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nobat-network-dev

  # Redis Commander (Redis Management)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nobat-redis-commander-dev
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:nobat_redis_password
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - nobat-network-dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

networks:
  nobat-network-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
